language: python

sudo: false  # false enables container-based build for fast boot times on Linux

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - pytest # or py.test for Python versions 3.5 and below